name: flutter_google_places
description: Google places autocomplete widgets for flutter. No wrapper, use https://pub.dartlang.org/packages/google_maps_webservice
version: 0.2.8
homepage: https://github.com/lejard-h/flutter_google_places
author: Hadrien Lejard (@lejard-h)
maintainer: Kevin Morelli (@KevMorelli)

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_api_headers: ">=0.1.0 <1.0.0"
  google_maps_webservice: ^0.0.19
  http: ">=0.11.0 <1.0.0"
  rxdart: ^0.25.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - packages/flutter_google_places/assets/google_black.png
    - packages/flutter_google_places/assets/google_white.png
