name: flutter_google_places_hoc081098
description: Google places autocomplete widgets for flutter. No wrapper, use https://pub.dartlang.org/packages/google_maps_webservice. Better flutter_google_places, updated by @hoc081098
version: 1.0.0-nullsafety.0
homepage: https://github.com/hoc081098/flutter_google_places
repository: https://github.com/hoc081098/flutter_google_places

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_api_headers: ^1.0.0
  google_maps_webservice: ^0.0.20-nullsafety.2
  http: ^0.13.0
  rxdart: ^0.26.0
  listenable_stream: ^1.0.0-nullsafety.1
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter:
  assets:
    - packages/flutter_google_places_hoc081098/assets/google_black.png
    - packages/flutter_google_places_hoc081098/assets/google_white.png
